name: composite action

runs:
  using: 'composite'
  steps:
  - name: Try to get env specific value
    run: |
      echo "${{ vars.MESSAGE }}"
      echo "${{ vars.URL }}"
      echo "${{ vars.FAKE }}"
    shell: bash
