name: Build test specs
on:
  push:

jobs:
  build-suites:
    runs-on: ubuntu-latest
    outputs:
      #matrix: "['\"integration/homepage.cy.js,integration/sidebar.cy.js\"']"
      matrix: ${{ steps.group-files.outputs.groups}}
    steps:
      - uses: actions/checkout@v3
      - name: group files
        id: group-files
        run: |
          suites=()
          files=($(find ./e2e/browser -iname '*.cy.js' -or -iname '*.cy.ts'))
          index=1
          while [ $index -le ${#files[@]} ] 
          do
            echo "check1 ${files[@]:0:3}"
            echo "check2 ${files[@]:$index:3}"
            echo "check3 ${files[@]:$index:3} | sed 's/ /,/g'"
            sub_group=$(echo ${files[@]:$index:3} | sed 's/ /,/g')
            echo "Current group is $sub_group"
            suites+=$sub_group
            index=$(( $index + 1 ))
          done
          echo "groups=$(jq -c -n '$ARGS.positional' --args "${suites[@]}")" >> $GITHUB_OUTPUT 


      #TODO: Add more steps to actually get the files correctly.

  compile-test-suites:
    needs: [build-suites]
    strategy:
      fail-fast: false
      matrix:
        test-spec: ${{ fromJson(needs.build-suites.outputs.matrix) }}   
    runs-on: ubuntu-latest
    steps:
      - run: echo "Here is the matrix ${{ matrix.test-spec }}"
